return { test = function() print('my test called') error() end }
